### ISSUE TITLE
To use the "java" command-line tool you need to install a JDK

### ISSUE THREAD

**Issue by jwulf** [Jorl17/jar2app#10]
A user without a JDK installed reports this error when opening my app, built with a bundled JDK:

<img width="1114" alt="screen shot 2016-12-19 at 8 11 43 pm" src="https://cloud.githubusercontent.com/assets/406975/21352624/14b5e51a-c70e-11e6-96f8-a92d5e8dd5db.png">

The command I used to build this file was:

```jar2app magikcraftLauncher.jar Magikcraft -n "Magikcraft"  -r /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk -i icon.icns -b io.magikcraft.launcher```

You can download the built here: https://s3.amazonaws.com/magikcraft-client/Magikcraft-MacOS.zip

It's a minecraft client launcher.

**Comment by jwulf** [comment]
<img width="667" alt="screen shot 2016-12-21 at 12 13 27 am" src="https://cloud.githubusercontent.com/assets/406975/21353611/8ceaf0bc-c712-11e6-875b-cbc48b9b101a.png">

Here's why - it launches another jar, and uses a command-line to do that.

If I modify the source code of my application, where should it be looking for the JDK, to see the bundled one?

**Comment by Jorl17** [comment]
I will look into this later tonight with my own tests when I have more free time. I'd just like to share a (possibly?) relevant link: https://stackoverflow.com/questions/33029752/osx-java-app-no-longer-finds-java-resources-folder-by-relative-url

Perhaps the straightforward solution might be [this one](https://stackoverflow.com/questions/12276795/how-can-i-access-resource-files-from-within-a-java-app-bundle-running-on-os-x)?

**Comment by Jorl17** [comment]
Have any of the solutions in the previous link worked?

The packaged JDK is at `<full path to .app>/Contents/Plugins/<jdk name>`. The issue here is getting the handle to the full path, because appbundler resets the current working directory to the user's home.

**Comment by Jorl17** [comment]
In commit https://github.com/Jorl17/jar2app/commit/479cc81b27f999bf252a17e354a9cfe07817861c I have added a command line option which allows setting the current working directory (this is done by adding an argument to the JVM options).

The default is now `$APP_ROOT/Contents`, so you can get the full path to the JDK with `System.getProperty("user.dir") + "/Plugins/<jdk name>/"`.

I'm hoping this helps you with your issue.

**Comment by Jorl17** [comment]
Closing this issue since the application now allows you to specify a working directory which can be relative to `$APP_ROOT` (the .app root) and a default is already in place. If there's any issues with that command, please open a new issue and I'll gladly look into it.
