### ISSUE TITLE
Changing name of Executable

### ISSUE THREAD

**Issue by farhanahmed95** [Jorl17/jar2app#14]
is there any method to rename JavaAppLauncher to App Display Name?

**Comment by Jorl17** [comment]
Hi,

Do you mean the actual executable inside the bundled .app, or do you mean to change the displayed app name (e.g. with the `-d` flag)?

**Comment by farhanahmed95** [comment]
yes actual executable

**Comment by nik312123** [comment]
@farhanahmed95 No offense is intended, but saying yes when asked to choose between two options is unhelpful.

**Comment by farhanahmed95** [comment]
@Jorl17 @nik312123 sorry for not providing proper information, basically I want to change JavaAppLauncher executable to Application name.

for example :
if App name Is XYZ.app then I also want executable name (JavaAppLauncher) to XYZ.

[
<img width="500" alt="screen shot 2017-11-20 at 3 53 10 pm" src="https://user-images.githubusercontent.com/8439438/33015081-486a3d7a-ce0b-11e7-9a0c-606a24f3e267.png">
](url)

**Comment by Jorl17** [comment]
Hi!

I'm so sorry it took me so long to answer, but life and work did not allow me to focus on this project until today.

I have added a flag to do exactly what you wanted (see commit 72864f27ff38911bc7816db78912e58f47767a28). You can just pass `-e <executable name>` and the name of the binary will be changed.

I recognize I am probably not going to be of much help this late to the occasion, but I hope it can still be useful to you and others!

Closing the issue, but feel free to leave a comment if there is any problem!
