### ISSUE TITLE
SplashScreen in MANIFEST.MF not working

### ISSUE THREAD

**Issue by nik312123** [Jorl17/jar2app#15]
So, I have an image in my jar file called loading.gif. In my manifest file, there is an attribute: SplashScreen-Image: loading.gif

This works perfectly fine as a .jar file, but upon using jar2app, it stops working for some reason.

**Comment by Jorl17** [comment]
I'm curious as to why this is happening. Is there a possibility for you to provide an example jar so that I can test it and try to find the issue? Thanks

**Comment by nik312123** [comment]
[SplashDemo.jar.zip](https://github.com/Jorl17/jar2app/files/1456251/SplashDemo.jar.zip)
Here is an example jar based on Oracle's Splash Screen example code.

**Comment by nik312123** [comment]
Hi! Any updates?

**Comment by Jorl17** [comment]
Hi, unfortunately I haven't had much time to look at the issue. I find it odd that the splash screen isn't loading, given that it is stored within the jar itself.

I seem to remember that `JavaAppLauncher`, which we use to launch the jars, changes the current working directory, and that could be a pointer to the issue...except for the fact that the data is stored within the jar itself...

**Comment by nik312123** [comment]
I think you are correct about the working directory change. The file I provided as an example used a relative file as an argument in the manifest. I tried changing it to an absolute path to the image on my desktop, and it worked. Is there a way around this?

**Comment by Jorl17** [comment]
There are several ways to go at this issue. You can try to package the file externally to the jar and then see if you can modify the generated plist file to change the current working directory, as [suggested here](http://smtp.grokbase.com/t/openjdk/macosx-port-dev/122w8hw0nh/appbundler-wrong-working-directory)

However, as you can see [https://stackoverflow.com/a/23284181/7481295](here), you can pass a `-splash:<path to file>` JVM option. If you modify the generated plist file and add `<string>-splash:$APP_ROOT/PATH_TO_SPLASH_GIF_RELATIVE_TO_APP_ROOT_HERE</string>` within the `<array>` portion of the `JVMOptions` key, you can get the JVM to point to the desired splash screen. I tried it here and it works

**Comment by nik312123** [comment]
Thank you very much! I got it working, but I figured out a way to do it all from command line, so it can be done in one step instead of having to edit the Info.plist and such.

jar2app exampleJar.jar (arguments) -j "-splash:\$APP_ROOT/Contents/Resources/loading.gif";cp path_to/loading.gif exampleApp.app/Contents/Resources

Thank you very much for your help. I appreciate it.
