### ISSUE TITLE
Package jar without jdk

### ISSUE THREAD

**Issue by nik312123** [Jorl17/jar2app#19]
Simply put, is there a way to not have the jdk added in the plugins folder? I do not need it, and I cannot disable it.

**Comment by Jorl17** [comment]
Hi, Can you specify what you mean by not being able to disable it? By default [it does not bundle any JDK](https://github.com/Jorl17/jar2app#does-jar2app-bundle-its-own-jrejdk-can-i-bundle-my-own).

Thanks!

**Comment by nik312123** [comment]
Hmm... I don't know what happened, but it fixed itself? It was probably some weird bug since I had my script set to bundle the JDK before and changed it to not do so.
