### ISSUE TITLE
You can't open the application "<NAME>.app" because it may be incomplete or damaged.

### ISSUE THREAD

**Issue by cjburkey01** [Jorl17/jar2app#2]
The app file created from the base command: `jar2app <NAME>.jar`

**Comment by Jorl17** [comment]
Hi!

Could you provide me with the jar you're using, so I can test it and debug it when I have time?

Thanks!

**Comment by Jorl17** [comment]
Bumping this due to the recent flow of new issues. Can you perhaps shine more info on this issue, @cjburkey01 ?

**Comment by Jorl17** [comment]
Closing issues without information and without any other reported instances of the problem
