### ISSUE TITLE
Operation not permitted?

### ISSUE THREAD

**Issue by SturmB** [Jorl17/jar2app#3]
I thought I'd give your program a try, but the install script doesn't appear to want to work. Here's what I've tried and their output:

```
apaches-iMac:Development apache$ git clone https://github.com/Jorl17/jar2app
Cloning into 'jar2app'...
remote: Counting objects: 62, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 62 (delta 30), reused 62 (delta 30), pack-reused 0
Unpacking objects: 100% (62/62), done.
Checking connectivity... done.
apaches-iMac:Development apache$ cd jar2app
apaches-iMac:jar2app apache$ ls
LICENSE			install.sh		jar2app_basefiles
LICENSING		jar2app			uninstall.sh
README.md		jar2app.py
apaches-iMac:jar2app apache$ chmod +x install.sh uninstall.sh
apaches-iMac:jar2app apache$ sudo ./install.sh
Password:
mkdir: /usr/bin/jar2app_basefiles: Operation not permitted
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
cp: /usr/bin/jar2app: Operation not permitted
chmod: /usr/bin/jar2app: No such file or directory
```

Those last few lines are the problem. I don't know what's going on. Any ideas?

Running Mac OS X El Capitan (10.11.6).

**Comment by Jorl17** [comment]
Hi. By default the script tries to install to /usr/bin. Since you are on El Capitan you probably have some form of SIP enabled which prevents this.

In the FAQ there is an [entry](https://github.com/Jorl17/jar2app#install-to-usrlocal-prefix) on how to install to the /usr/local/ prefix which I think still has write-access with SIP enabled. Could you perhaps give that a try? I admit the install scripts are flaky, and I haven't really checked them in a while, so do say if there are any more issues.

**Comment by SturmB** [comment]
Wow, that was *fast*!

Okay, so it seems that the program installed to /usr/local, since I didn't receive any messages (errors or otherwise) after running the `sudo ./install.sh /usr/local` command. However, the program does not seem to run.

Depending upon from where I try to run the program, I'll get one of two possible error messages that are similar:

```
apaches-iMac:local apache$ jar2app ~/Development/ArtDept.jar
-bash: jar2app: command not found
apaches-iMac:local apache$ cd ~/Development/
apaches-iMac:Development apache$ /usr/local/jar2app ArtDept.jar
env: python3: No such file or directory
apaches-iMac:Development apache$ 
```

I suppose it might be because Python isn't installed, even though I thought it was. How can I tell and, more importantly, how can I install it in the best way possible?

**Comment by Jorl17** [comment]
Yes, you are correct. Firstly, you should add /usr/local/bin to your `PATH` so you don't have to prefix the program every time. 

Regarding Python3, the best way I can think of installing it is using [Homebrew](http://brew.sh). Grab brew and then `brew install python3`. OS X comes pre-packaged with a version of python2, but, as far as I know, not python3. By the way, I'm not sure but I think Homebrew already adds /usr/local/bin to your `PATH`.

**Comment by SturmB** [comment]
Okay, I do have Homebrew installed from when I was playing with Ruby earlier this year. However, once again, permission denied errors appear. Since it's a Homebrew problem, I don't expect you to troubleshoot it; Maybe I'll just get an installer from the Python site. And while I'm at it, I'll reference how to add a new directory entry to my PATH environment variable. Yes, I'm still a greenhorn.

**Comment by SturmB** [comment]
Okay, got it all working now.

Started by updating the `PATH` by following [this guide](https://coolestguidesontheplanet.com/add-shell-path-osx/), then reloading the `.bash_profile`.

Then I updated Homebrew, followed by running the various Homebrew cleaning steps found at [this Stackoverflow discussion](http://stackoverflow.com/questions/13088998/homebrew-python-installing). I was then able to get Python3 installed successfully and now your jar2app program works! Yay!

Thanks for the awesome help!

**Comment by Jorl17** [comment]
I'm glad it all worked out! If you have any problems, feel free to open up new issue here :)
