### ISSUE TITLE
How to package extra files into app

### ISSUE THREAD

**Issue by HyWell** [Jorl17/jar2app#31]
Directory Structure:
`
xxxx.jar
data.db
`
Java code:
`
jdbc:sqlite:data.db
`
Run jar need data.db
Use`jar2app XXXX.jar -j "-XstartOnFirstThread" -r /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk`。
Open app prompt error
`not found data.db`

**Comment by veronicakulikova** [comment]
I didn't have any problem accessing a database in <app>.app/Contents when manually placed.

-Used the example code from [here](http://www.sqlitetutorial.net/sqlite-java/sqlite-jdbc-driver/)
-Used `"jdbc:sqlite:chinook.db"` as the url (chinook.db downloaded from [here](http://www.sqlitetutorial.net/sqlite-sample-database/))
-Ran `jar2app source/jdbctest.jar -r /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk`
-Database was cp-ed into `<app>.app/Contents/chinook.db` after jar2app was run
Result: The database was successfully located, and queries returned valid data.

I believe you'll have to be more specific about what version of the sqlite library you're using and the code that actually calls into jdbc.

**Comment by HyWell** [comment]
sqlite library:sqlite-jdbc-3.21.0.jar
![image](https://user-images.githubusercontent.com/21263451/48659291-c4531b00-ea89-11e8-9f02-54336a40aad2.png)
cp-ed，run
![image](https://user-images.githubusercontent.com/21263451/48659335-45aaad80-ea8a-11e8-9fb0-39e0d63c6bdc.png)

**Comment by HyWell** [comment]
![image](https://user-images.githubusercontent.com/21263451/48659636-0c287100-ea8f-11e8-89b7-c86345ac3950.png)
its ok

**Comment by veronicakulikova** [comment]
Weird. Well, I was using an old jar2app version. Regression?
My 10.14.1 MacBook Pro (which is what I used) is in the shop for a few days. I'll retry on an older model MacBook in ~12h
Do you get an SQLException when you don't use the File.exists() check?

**Comment by HyWell** [comment]
My MacBook Pro
![image](https://user-images.githubusercontent.com/21263451/48659765-206d6d80-ea91-11e8-90c1-6575c38860bf.png)
jar2app version
![image](https://user-images.githubusercontent.com/21263451/48659785-3d09a580-ea91-11e8-8c0d-da6216eee3bb.png)

**Comment by veronicakulikova** [comment]
A File.exists() check fails for me when I set things up as you have, but my driver still finds the database. I used `sqlite-jdbc-3.23.1.jar`
<img width="648" alt="image" src="https://user-images.githubusercontent.com/10523871/49261914-edb06700-f3f8-11e8-8045-5a40acf2aa13.png">
<img width="510" alt="image" src="https://user-images.githubusercontent.com/10523871/49261940-10428000-f3f9-11e8-8162-721bd1f2d9a1.png">

**Comment by Lucina** [comment]
<img width="1109" alt="screen shot 2018-11-29 at 5 50 08 pm" src="https://user-images.githubusercontent.com/10523871/49263435-631f3600-f3ff-11e8-8b2c-92af361050a8.png">
<img width="1414" alt="screen shot 2018-11-29 at 5 49 22 pm" src="https://user-images.githubusercontent.com/10523871/49263440-69adad80-f3ff-11e8-8354-fb1949671f33.png">

`user.home` ends up being `/Users/<name>`
`user.dir` ends up being `/.../<app>.app/Contents`
It looks like `File.exists()` (and `File.createNewFile()`) use `user.home` for relative paths. `File.getAbsoluteFile()` and `File.getAbsolutePath()` resolve using `user.dir`

If you use `File.getAbsoluteFile().exists()` you should be set.
<img width="804" alt="screen shot 2018-11-29 at 5 55 25 pm" src="https://user-images.githubusercontent.com/10523871/49263646-42a3ab80-f400-11e8-8ab1-9f61ac61374c.png">
<img width="375" alt="screen shot 2018-11-29 at 5 55 57 pm" src="https://user-images.githubusercontent.com/10523871/49263651-46cfc900-f400-11e8-9538-b4ce577c72a5.png">

**Comment by HyWell** [comment]
Thank you very much！
Follow your suggestions, successfully connect。
cp data.db to xxxx.app/Contents,it's work。
