### ISSUE TITLE
Adding icon using -i parameter does not change the icon of the .app application

### ISSUE THREAD

**Issue by kbartman** [Jorl17/jar2app#35]
jar2app doesn't change the displayed icon shown in finder. The only way I've found that this can be done is to open the icon in preview copy and paste it into the Get Info top left icon area of the application. Can this be fixed so this step is not needed.

Example Usage:
`$ jar2app myapp.jar -n "MyApp" -i "myappicon.icns"
`
MyApp.app shows a script icon and not the icon chosen in the command.

This was done with Mac OS Verison: macOS Mojave version 10.14.2

**Comment by Lucina** [comment]
Just a thought: does the .icns you're trying to add have icons of all valid resolutions?
If so, should be something Mojave does. It was fine on High Sierra.

**Comment by Lucina** [comment]
<img width="1276" alt="screen shot 2019-01-20 at 2 17 49 pm" src="https://user-images.githubusercontent.com/10523871/51445821-5cee5d00-1cbe-11e9-9504-8fd8a8a9b2fb.png">
The program creates an app with a proper icon for me. Mojave 10.14.2 on a late 2017 MBP

**Comment by kbartman** [comment]
Thanks @veronicakulikova, Yes this was an issue with the icon I created. I created an iconset with all the necessary resolutions and used the iconutil command included in macOS and all is well.
