### ISSUE TITLE
Bundling .jar file error on execution

### ISSUE THREAD

**Issue by JC-ProgJava** [Jorl17/jar2app#47]
"Unable to load Java Runtime Environment" dialog shows on execution of .app created.

**Comment by riina** [comment]
Check #39 and #43 for solutions. If you’re able to use JDK 14, jpackage can be better for fully isolated .app images.

**Comment by lehigh123** [comment]
Can you provide a link to jpackage? I got the same issue as @JC-ProgJava

**Comment by Lucina** [comment]
It's provided in JDK 14

**Comment by JC-ProgJava** [comment]
I am currently using OpenJDK-provided JDK 14 and am still having the same error.

**Comment by JC-ProgJava** [comment]
Below is how I executed and output given.
<img width="413" alt="Screen Shot 2020-07-08 at 9 28 06 AM" src="https://user-images.githubusercontent.com/61588096/86863442-c43fdd00-c0fd-11ea-8d56-8891b2a579db.png">
<img width="961" alt="Screen Shot 2020-07-08 at 9 28 31 AM" src="https://user-images.githubusercontent.com/61588096/86863448-c73acd80-c0fd-11ea-9203-662b9fffa41b.png">

**Comment by Lucina** [comment]
JavaAppLauncher won’t work at all beyond JDK/JRE 8. Try [universalJavaApplicationStub](https://github.com/tofi86/universalJavaApplicationStub) and `-x`.
