### ISSUE TITLE
uploading to app store

### ISSUE THREAD

**Issue by ddyer0** [Jorl17/jar2app#48]
I've hit a wall trying to upload apps created by jar2app to the app store.  The complaint (from transporter) is that
it can't find the bundle id.
https://stackoverflow.com/questions/59761535/error-from-transporter-failed-to-get-the-apps-bundle-id

My hope, entering this as an issue for jar2app, is that it's some subtle and otherwise meaningless feature
of the app written by jar2app that is confusing transporter.

Here is the script I use to create the app, and bundle it for transporter.
#!/bin/csh
./jar2app boardspace.jar -i boardspace.icns -n "boardspace" -d "boardspace.net" -b "com.boardspace.app.launcher" -v 1.0
codesign -s "Developer ID" boardspace.app/Contents/MacOS/JavaAppLauncher
codesign -s "Developer ID" boardspace.app/Contents/Resources/boardspace.icns
codesign -s "Developer ID" boardspace.app/Contents/Java/boardspace.jar
codesign -s "Developer ID" boardspace.app

productbuild --component boardspace.app /applications --sign "Developer ID"  --identifier com.boardspace.launcher.app boardspace.pkg

**Comment by Lucina** [comment]
Just a thought, maybe `--identifier` in your productbuild invocation should be `com.boardspace.launcher`

Assuming you're using a newer JDK and bundling a runtime (since you're distributing to the App Store), I'd consider using jpackage instead.

**Comment by ddyer0** [comment]
Thanks for the thought - the mismatch in package names is indeed suspicious, but matching doesn't help.    
I think I considered jpackage too, but settled on jar2app for some reason I didn't document.  Maybe I'll re-evaluate.

**Comment by ddyer0** [comment]
Some progress on this front - the missing bits include a PkgInfo file and some properties in info.plist 
-- apparently the LSMinimumSystemVersion property is mandatory, and perhaps also the NSHumanReadableCopyright 
property can't be blank.   After fixing these things in the .app package, I was successful sending to the app store.
Naturally, more complaints came from there, but at least an essential step was made.
