### ISSUE TITLE
global name 'FileExistsError' is not defined

### ISSUE THREAD

**Issue by JohnnyLe** [Jorl17/jar2app#5]
I test in Window with Python 2.7.12 environment and got bellow error. Do you have any idea?

![image](https://cloud.githubusercontent.com/assets/1794584/20803896/66b29d4e-b823-11e6-8ae0-3b15a290943c.png)

**Comment by Jorl17** [comment]
Hi. jar2app was made for Python3, not Python2, though I might look into porting it very soon

**Comment by Jorl17** [comment]
I've just pushed A Python2 compatible version. Could you pull and try it out? Thanks!

**Comment by JohnnyLe** [comment]
Brilliant! Thank you very much @Jorl17 . I will try again and let you know the result.

**Comment by Jorl17** [comment]
Hi!

Can you confirm this issue was fixed? Was hoping to close this issue.

Thanks :)

**Comment by JohnnyLe** [comment]
Hi @Jorl17 

Sorry for late response. Yes, I confirmed that this issue was fixed.
Thank you for your effort.
