### ISSUE TITLE
how is the jar launched

### ISSUE THREAD

**Issue by awright424** [Jorl17/jar2app#6]
I see that in the Macos folder is a javalauncher file. how is that used to launch the package jar? I also codesigned the resulting .app but still seem to have issues with gatekeeper not allowing the app to launch

`Termination Reason:    Namespace CODESIGNING, Code 0x1`

**Comment by Jorl17** [comment]
[This FAQ entry](https://github.com/Jorl17/jar2app#how-does-it-work) might shine some light on what the JavaLauncher file does. We pass some parameters in the .plist file, such as the main class of the JAR or the path to the JRE
