### ISSUE TITLE
jar packaging gatekeeper

### ISSUE THREAD

**Issue by awright424** [Jorl17/jar2app#7]
how is the jar packaged and when it is, is it in conformance with gatekeeper on osx 10.12.1? I have been able to codesign this without problem but when attempting to launch or verifying with spctl it says it is rejected.

**Comment by Jorl17** [comment]
The jar is packaged using https://java.net/projects/appbundler to launch it (see [here](https://github.com/Jorl17/jar2app#how-does-it-work) for more info).

In the FAQ, I note that I have not signed any binaries built with jar2app, and it is not ready for production "out of the box" (i.e. you may need to fiddle with some command line options or manually edit the generated plist file).

I did a quick google search and some people suggested using the `--deep` option when code signing (others noted that it should be used for emergency repairs only (see [here](https://stackoverflow.com/questions/26938414/code-sign-java-app-for-os-x-gatekeeper)).

Some sources mentioned signing using the following syntax `codesign -v -f -s "Developer ID Application"  "myapp.app"`. Excuse my ignorance regarding this issue. Perhaps some more information regarding the output of `spctl` could help me debug the issue with you? :)

**Comment by Jorl17** [comment]
Quick bump to know if there's anything that `jar2app` needs to do to help you with the signing process

**Comment by Jorl17** [comment]
Closing issues without any clear relationship with jar2app
