### ISSUE TITLE
Operation not permitted copying Localizable strings

### ISSUE THREAD

**Issue by jwulf** [Jorl17/jar2app#9]
I get the following error message when bundling my jar:

```
OSError: [Errno 1] Operation not permitted: './Magikcraft.app/Contents/Resources/en.lproj/Localizable.strings'
```

There is a `./Magikcraft.app/Contents/Resources` folder in the output, but no `en.lproj` one.

**Comment by jwulf** [comment]
Works if I run it as root using sudo.

**Comment by Jorl17** [comment]
Hi!

Do you think this was an issue with jar2app or merely a permissions issue?

Thanks :)

**Comment by jwulf** [comment]
I was running it in an empty directory. If jar2app is not designed to require sudo, then I think it's an issue.

**Comment by Jorl17** [comment]
Thanks, it's fixed now.
